/**
 * PDF proposal generator for solar rooftop analysis
 */

import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import { formatINR } from "./calculations";

export interface PDFProposalData {
  address?: string;
  lat: number;
  lon: number;
  roofArea: number;
  systemSize: number;
  panelCount?: number;
  annualGeneration: number;
  annualGHI: number;
  subsidy: number;
  systemCostLow: number;
  systemCostHigh: number;
  netCostLow: number;
  netCostHigh: number;
  annualSavings: number;
  paybackPeriod: number;
  savings10Year: number;
  savings25Year: number;
  discomName: string;
  discomState: string;
  monthlyConsumption: number;
  consumptionScope: "household" | "building";
}

export async function generatePDFProposal(
  data: PDFProposalData,
  chartElement?: HTMLElement | null
): Promise<void> {
  const doc = new jsPDF("p", "mm", "a4");
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  let y = 20;

  const addText = (text: string, fontSize = 10) => {
    doc.setFontSize(fontSize);
    doc.text(text, margin, y);
    y += fontSize * 0.5 + 2;
  };

  const addSection = (title: string) => {
    y += 5;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
  };

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Solar Rooftop Proposal", margin, y);
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  if (data.address) {
    doc.text(`Address: ${data.address}`, margin, y);
    y += 6;
  }
  doc.text(`Location: ${data.lat.toFixed(4)}°N, ${data.lon.toFixed(4)}°E`, margin, y);
  y += 6;
  doc.text(`Electricity: ${data.discomState} / ${data.discomName}`, margin, y);
  y += 6;
  doc.text(`Consumption: ${data.monthlyConsumption} kWh/month (${data.consumptionScope})`, margin, y);
  y += 10;

  addSection("System Overview");
  doc.text(`Roof Area: ${data.roofArea} m²`, margin, y);
  y += 6;
  doc.text(`System Size: ${data.systemSize} kW`, margin, y);
  y += 6;
  if (data.panelCount) {
    doc.text(`Panels: ${data.panelCount}`, margin, y);
    y += 6;
  }
  doc.text(`Annual Generation: ${data.annualGeneration.toLocaleString()} kWh`, margin, y);
  y += 6;
  doc.text(`Solar GHI: ${data.annualGHI.toFixed(2)} kWh/m²/day`, margin, y);
  y += 10;

  addSection("Cost Breakdown");
  doc.text(`System Cost: ${formatINR(data.systemCostLow)} - ${formatINR(data.systemCostHigh)}`, margin, y);
  y += 6;
  doc.text(`PM Surya Ghar Subsidy: ${formatINR(data.subsidy)}`, margin, y);
  y += 6;
  doc.text(`Net Cost: ${formatINR(data.netCostLow)} - ${formatINR(data.netCostHigh)}`, margin, y);
  y += 10;

  addSection("Savings & ROI");
  doc.text(`Annual Savings: ${formatINR(data.annualSavings)}`, margin, y);
  y += 6;
  doc.text(`Payback Period: ${data.paybackPeriod === Infinity ? "N/A" : `${data.paybackPeriod} years`}`, margin, y);
  y += 6;
  doc.text(`10-Year Savings: ${formatINR(data.savings10Year)}`, margin, y);
  y += 6;
  doc.text(`25-Year Savings: ${formatINR(data.savings25Year)}`, margin, y);
  y += 10;

  if (chartElement) {
    try {
      const canvas = await html2canvas(chartElement, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: "#ffffff",
      });
      const imgData = canvas.toDataURL("image/png");
      const imgWidth = pageWidth - margin * 2;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      if (y + imgHeight > 270) {
        doc.addPage();
        y = 20;
      }
      doc.addImage(imgData, "PNG", margin, y, imgWidth, Math.min(imgHeight, 80));
      y += Math.min(imgHeight, 80) + 10;
    } catch {
      doc.text("(Chart could not be embedded)", margin, y);
      y += 6;
    }
  }

  addSection("Assumptions");
  doc.text("• 80% usable roof area, 10 m² per kW", margin, y);
  y += 6;
  doc.text("• 75% performance ratio", margin, y);
  y += 6;
  doc.text("• 0.5% annual panel degradation", margin, y);
  y += 6;
  doc.text("• 5% annual electricity tariff escalation", margin, y);
  y += 6;
  doc.text("• Data: NASA POWER API, OSM building footprints", margin, y);
  y += 10;

  doc.setFontSize(8);
  doc.text(`Generated by Solar Rooftop India · ${new Date().toLocaleDateString()}`, margin, 285);

  doc.save("solar-rooftop-proposal.pdf");
}
